language: ruby
rvm:
  - 2.4.1
services:
  - elasticsearch
before_script:
  - sleep 10
env:
  ES_URL=http://localhost:9200
  FIND_A_STANDARD_USERNAME=username
  FIND_A_STANDARD_PASSWORD=password
  FIND_A_STANDARD_INDEX=find_a_standard_test
